export const types = {
  FETCH_RECENT_NEARBY_NOTABLE_SIGHTINGS_REQUEST:
    'FETCH_RECENT_NEARBY_NOTABLE_SIGHTINGS_REQUEST',
  FETCH_RECENT_NEARBY_NOTABLE_SIGHTINGS_SUCCESS:
    'FETCH_RECENT_NEARBY_NOTABLE_SIGHTINGS_SUCCESS',
  FETCH_RECENT_NEARBY_NOTABLE_SIGHTINGS_FAILURE:
    'FETCH_RECENT_NEARBY_NOTABLE_SIGHTINGS_FAILURE',
  LOG_POSITION: 'LOG_POSITION',
};
