const types = {
  REQUEST_NOTABLE_SIGHTINGS: "REQUEST_NOTABLE_SIGHTINGS",
  RECEIVE_NOTABLE_SIGHTINGS: "RECEIVE_NOTABLE_SIGHTINGS",
  SET_SELECTED_STATE: "SET_SELECTED_STATE"
};

export default types;
